name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - lint
          - check
          - test
          - build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set variables
        id: vars
        run: |
          tool_versions=`cat ./.tool-versions`
          bun_version=`echo $tool_versions | awk '{print $2}'`
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ steps.vars.outputs.bun_version }}
      - name: Install dependencies
        run: bun install
      - name: Set Playwright up
        if: matrix.job == 'test'
        run: bunx playwright install
      - name: Run build check
        run: bun run ${{ matrix.job }}

  tag-version:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Tag new version
        run: |
          git reset --hard
          git config --global user.name "${{github.triggering_actor}}"
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          npm version patch -m 'Bump version to %s [skip ci]'
          git push --no-verify --tags
