name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install tools
        uses: asdf-vm/actions/install@v2
      - name: Install dependencies
        run: bun install
      # temporarily disabled, pending update in eslint-plugin-svelte
      # https://github.com/sveltejs/eslint-plugin-svelte/issues/652
      #- name: Lint code
      #  run: bun run lint
      - name: Run svelte checks
        run: bun run check
      - name: Run tests
        run: bun run test
